Repository alexa/alexa-skills-kit-sdk-for-python, pull requests merged in 2018-11, with the labels that each got.

#46 Add helper function for matching CanFulfill Intent name
  ask-sdk-core/ask_sdk_core/utils/__init__.py
  ask-sdk-core/ask_sdk_core/utils/predicate.py
  ask-sdk-core/tests/unit/test_utils.py
Labels: feature-request:sdk

#48 Deserialize only if payload is not None
  ask-sdk-core/ask_sdk_core/serialize.py
Labels: bug

#50 Refactor dependencies for python versions
  ask-sdk-core/ask_sdk_core/__version__.py
  ask-sdk-core/setup.py
  ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/__version__.py
  ask-sdk-dynamodb-persistence-adapter/setup.py
  ask-sdk-runtime/ask_sdk_runtime/__version__.py
  ask-sdk-runtime/requirements.txt
  ask-sdk-runtime/setup.py
  ask-sdk/ask_sdk/__version__.py
  ask-sdk/setup.py
Labels: bug

#51 Add missing model docs
  docs/en/models/ask_sdk_model.dialog.rst
  docs/en/models/ask_sdk_model.interfaces.alexa.presentation.apl.rst
  docs/en/models/ask_sdk_model.interfaces.alexa.presentation.rst
  docs/en/models/ask_sdk_model.interfaces.alexa.rst
  docs/en/models/ask_sdk_model.interfaces.amazonpay.model.request.rst
  docs/en/models/ask_sdk_model.interfaces.amazonpay.model.rst
  docs/en/models/ask_sdk_model.interfaces.amazonpay.rst
  docs/en/models/ask_sdk_model.interfaces.amazonpay.v1.rst
  docs/en/models/ask_sdk_model.interfaces.viewport.rst
  docs/en/models/ask_sdk_model.services.directive.rst
  docs/en/models/ask_sdk_model.services.game_engine.rst
Labels: documentation
