Repository alexa/alexa-skills-kit-sdk-for-python, pull requests merged in 2019-04, with the labels that each got.

#71 Add custom css to wrap the overflow values in documentation
  docs/en/_static/css/custom.css
  docs/en/conf.py
Labels: documentation

#74 Fix for type comments and adding py.typed files for mypy linters
  .travis.yml
  ask-sdk-core/ask_sdk_core/api_client.py
  ask-sdk-core/ask_sdk_core/attributes_manager.py
  ask-sdk-core/ask_sdk_core/dispatch_components/exception_components.py
  ask-sdk-core/ask_sdk_core/serialize.py
  ask-sdk-core/ask_sdk_core/skill.py
  ask-sdk-core/ask_sdk_core/skill_builder.py
  ask-sdk-core/tests/unit/test_attributes_manager.py
  ask-sdk-core/tests/unit/test_skill.py
  ask-sdk-core/tests/unit/test_skill_builder.py
  ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/py.typed
  ask-sdk-runtime/ask_sdk_runtime/dispatch.py
  ask-sdk-runtime/ask_sdk_runtime/dispatch_components/exception_components.py
  ask-sdk-runtime/ask_sdk_runtime/dispatch_components/py.typed
  ask-sdk-runtime/ask_sdk_runtime/dispatch_components/request_components.py
  ask-sdk-runtime/ask_sdk_runtime/py.typed
  ask-sdk-runtime/ask_sdk_runtime/skill.py
  ask-sdk-runtime/ask_sdk_runtime/utils.py
  ask-sdk-runtime/tests/unit/test_dispatch.py
  ask-sdk/ask_sdk/py.typed
  ask-sdk/ask_sdk/standard.py
Labels: feature-request:sdk

#75 Add check for device information in get_device_id utility function
  ask-sdk-core/ask_sdk_core/utils/request_util.py
  ask-sdk-core/tests/unit/test_utils.py
Labels: bug

#77 Add delete attributes feature to Persistence Adapter
  ask-sdk-core/ask_sdk_core/attributes_manager.py
  ask-sdk-core/tests/unit/data/mock_persistence_adapter.py
  ask-sdk-core/tests/unit/test_attributes_manager.py
  ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/adapter.py
  ask-sdk-dynamodb-persistence-adapter/tests/unit/test_adapter.py
Labels: feature-request:sdk

#79 Adding Code Sample Section for UpsServiceClient
  docs/en/SERVICE_CLIENTS.rst
Labels: documentation

#80 Documentation for out-of-session service clients, missing models
  README.rst
  docs/en/OUT_OF_SESSION_SERVICE_CLIENTS.rst
  docs/en/REQUEST_PROCESSING.rst
  docs/en/RESPONSE_BUILDING.rst
  docs/en/SDK_SUPPORTED_ALEXA_CAPABILITIES.rst
  docs/en/SERVICE_CLIENTS.rst
  docs/en/index.rst
  docs/en/models/ask_sdk_model.interfaces.alexa.presentation.apl.rst
  docs/en/models/ask_sdk_model.services.lwa.rst
  docs/en/models/ask_sdk_model.services.proactive_events.rst
  docs/en/models/ask_sdk_model.services.rst
  docs/en/models/ask_sdk_model.services.skill_messaging.rst
Labels: documentation

#81 Update webservice docstrings to reflect in rtd documentation
  README.rst
  ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py
  ask-sdk-webservice-support/ask_sdk_webservice_support/verifier_constants.py
  ask-sdk-webservice-support/ask_sdk_webservice_support/webservice_handler.py
  docs/en/SAMPLE_SKILLS.rst
  docs/en/SERVICE_CLIENTS.rst
  docs/en/api/webservice.rst
Labels: documentation

#83 Set custom user agent correctly, run webservice tests on tox
  ask-sdk-webservice-support/ask_sdk_webservice_support/__version__.py
  ask-sdk-webservice-support/ask_sdk_webservice_support/webservice_handler.py
  ask-sdk-webservice-support/tests/unit/test_webservice_handler.py
  django-ask-sdk/django_ask_sdk/__version__.py
  django-ask-sdk/django_ask_sdk/skill_adapter.py
  django-ask-sdk/tests/unit/test_skill_adapter.py
  flask-ask-sdk/flask_ask_sdk/__version__.py
  flask-ask-sdk/flask_ask_sdk/skill_adapter.py
  flask-ask-sdk/tests/unit/test_skill_adapter.py
  scripts/ci/run_tests
  scripts/ci/sdk_install
  tox.ini
Labels: bug
