Repository alexa/alexa-skills-kit-sdk-for-python, pull requests merged in 2019-08, with the labels that each got.

#109 Allow out-of-session requests
  ask-sdk-core/ask_sdk_core/attributes_manager.py
  ask-sdk-core/tests/unit/test_attributes_manager.py
  ask-sdk-core/tests/unit/test_skill_builder.py
Labels: bug

#111 Add SkillAdapter import to example code
  flask-ask-sdk/README.rst
Labels: documentation

#110 Change decorator returned by request_handler to return the handler function
  ask-sdk-runtime/ask_sdk_runtime/skill_builder.py
  ask-sdk-runtime/tests/unit/test_skill_builder.py
Labels: bug

#113 Change webservice adapters documentation for GA release
  README.ja.rst
  README.rst
  ask-sdk-webservice-support/README.rst
  ask-sdk-webservice-support/ask_sdk_webservice_support/py.typed
  ask-sdk-webservice-support/setup.py
  django-ask-sdk/README.rst
  django-ask-sdk/django_ask_sdk/py.typed
  django-ask-sdk/setup.py
  flask-ask-sdk/README.rst
  flask-ask-sdk/flask_ask_sdk/py.typed
  flask-ask-sdk/setup.py
Labels: enhancement

#114 Adding Template Resolvers for response generations
  ask-sdk-core/.gitignore
  ask-sdk-core/CHANGELOG.rst
  ask-sdk-core/README.rst
  ask-sdk-core/ask_sdk_core/dispatch_components/py.typed
  ask-sdk-core/ask_sdk_core/dispatch_components/request_components.py
  ask-sdk-core/ask_sdk_core/exceptions.py
  ask-sdk-core/ask_sdk_core/handler_input.py
  ask-sdk-core/ask_sdk_core/py.typed
  ask-sdk-core/ask_sdk_core/skill.py
  ask-sdk-core/ask_sdk_core/skill_builder.py
  ask-sdk-core/ask_sdk_core/utils/py.typed
  ask-sdk-core/ask_sdk_core/utils/view_resolver.py
  ask-sdk-core/ask_sdk_core/view_resolvers/__init__.py
  ask-sdk-core/ask_sdk_core/view_resolvers/access_ordered_template_content.py
  ask-sdk-core/ask_sdk_core/view_resolvers/file_system_template_loader.py
  ask-sdk-core/ask_sdk_core/view_resolvers/locale_template_enumerator.py
  ask-sdk-core/ask_sdk_core/view_resolvers/lru_cache.py
  ask-sdk-core/ask_sdk_core/view_resolvers/py.typed
  ask-sdk-core/ask_sdk_core/view_resolvers/template_content.py
  ask-sdk-core/ask_sdk_core/view_resolvers/template_factory.py
  ask-sdk-core/tests/unit/test_file_system_template_loader.py
  ask-sdk-core/tests/unit/test_locale_template_enumerator.py
  ask-sdk-core/tests/unit/test_lru_cache.py
  ask-sdk-core/tests/unit/test_template_factory.py
  ask-sdk-core/tests/unit/test_view_resolver_util.py
  ask-sdk-jinja-renderer/.coveragerc
  ask-sdk-jinja-renderer/CHANGELOG.rst
  ask-sdk-jinja-renderer/MANIFEST.in
  ask-sdk-jinja-renderer/README.rst
  ask-sdk-jinja-renderer/ask_sdk_jinja_renderer/__init__.py
  ask-sdk-jinja-renderer/ask_sdk_jinja_renderer/__version__.py
  ask-sdk-jinja-renderer/ask_sdk_jinja_renderer/jinja_template_renderer.py
  ask-sdk-jinja-renderer/ask_sdk_jinja_renderer/py.typed
  ask-sdk-jinja-renderer/requirements.txt
  ask-sdk-jinja-renderer/setup.cfg
  ask-sdk-jinja-renderer/setup.py
  ask-sdk-jinja-renderer/tests/__init__.py
  ask-sdk-jinja-renderer/tests/unit/__init__.py
  ask-sdk-jinja-renderer/tests/unit/test_jinja_template_renderer.py
  ask-sdk-runtime/.gitignore
  ask-sdk-runtime/ask_sdk_runtime/skill.py
  ask-sdk-runtime/ask_sdk_runtime/skill_builder.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/__init__.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/abstract_template_cache.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/abstract_template_enumerator.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/abstract_template_factory.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/abstract_template_loader.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/abstract_template_renderer.py
  ask-sdk-runtime/ask_sdk_runtime/view_resolvers/py.typed
  ask-sdk-runtime/tests/unit/test_skill_builder.py
Labels: enhancement, feature-request:sdk
